---

- name: Creating containers and installing packages
  hosts: linux
  become: true
  gather_facts: no
  vars:
    ansible_python_interpreter: /home/Ahmer/anaconda3/bin/python
    dockerfile_folder: dockerfile-folder
    docker_image_name: ssh_os:1
    docker_container_name: test_os
    patting_ssh_port: 1122
    patting_http_port: 80

  tasks:
    - name: Copy dockerfile
      copy:
        src: "./{{dockerfile_folder}}"
        dest: /tmp/


    - name: Build docker image from Dockerfile
      docker_image:
        name: "{{docker_image_name}}"
        build:
          # pull: yes
          path: "/tmp/{{ dockerfile_folder }}/"
        source: build
        state: present

    - name: Launch docker container
      docker_container:
        name: "{{docker_container_name}}"
        image: "{{docker_image_name}}"
        state: started
        ports:
         - " {{ patting_ssh_port }}:22"
         - " {{ patting_http_port }}:8080"
      register: docker_info

    - name: Update Inventory file
      lineinfile:
        path: /etc/ansible/hosts
        insertafter: '^[containers]'
        firstmatch: yes
        line: "{{docker_info.ansible_facts.docker_container.NetworkSettings.IPAddress}}"
        state: present



    # - name: Create default containers
    #   docker_container:
    #     name: ubuntu
    #     image: redis:6.2
    #     command: sleep 1d
    #     state: present


    # - name: Create a ubuntu container
    #   docker_container:
    #    name: ubuntu-container
    #    image: ubuntu:20.04
    #    volumes:
    #     - ./u-dir
